### ISSUE TITLE
Process to merge automatic branches into master

### ISSUE THREAD

**Issue by sbates130272** [Eideticom/eid-images#2]
@TyKeeling has developed a system that allows eid-ansible to use Packer and Ansible to create a disk image and then push this to a branch of eid-images (see eid-packer-ubuntu-focal).

However we (@wadelockhart @lsgunth) need to determine a process for merging the branches we want into master, We need a directory naming convention and also a way to make the top-level README more generic and put per-image README somewhere else.

I propose the following:

1. Write a generic README.md that can be constant as we add new images. It should discuss how to add a new image and how to pull this repo if you need too.
2. Add a README-<subdir>.md for each top-level image folder we want.
3. Keep qemu.py folder but add folders based on distro (e.g. ubuntu in this case).

I await feedback!

**Comment by sbates130272** [comment]
I expect @TyKeeling to implement whatever we decide in this discussion.

**Comment by wadelockhart** [comment]
Hey Stephen, if I may take a step back - the initial setup of the eid-images repo was so that we could store 'shrunken' images and pull them down for buildbot tests automatically. 

What are the benefits of storing the 'other' images (such as created by Tyler) in eid-images as opposed to building them from scratch or storing on the NFS?

I know there are bandwidth caps for github, etc. and I am wondering how the decision to put reproducible images into github plays into that?

I am probably just out of the loop as to what these other images are for...

**Comment by sbates130272** [comment]
@wadelockhart the original intent for eid-images was actually for customers so they did not have to setup their VM images from scratch. I think the buildbot stuff came after (which is why the repo is public and not private). The GitHub limitations became clear only once we started pushing and pulling images and hit those limits.

I am happy to look at other options for customer facing images but I am not sure what they might be (maybe an S3 bucket or the equivalent on Azure).

**Comment by wadelockhart** [comment]
@sbates130272 - Hey Stephen, now that you mention it, I do recall the discussion around a customer-facing repository for images. I likely just forgot that the intended option was eid-images.

I think github is fine for customer image access, so long as we can separate that access (which I imagine is the intent). For example, we may want Customer A to access an ubuntu-focal image, but not any images in our qemu.py folder.

Let me discuss with Logan during our Wednesday meeting and get his thoughts and we will get rolling on this...

**Comment by sbates130272** [comment]
@wadelockhart eid-images is public facing so anyone can download any of the images on there any time they want.

**Comment by wadelockhart** [comment]
1. The first thing we need to agree upon is if github is the place for these images. For now, I assume it is and will discuss with Logan further tomorrow. That discussion could make the following items less consequential.

2. I guess the next thing we would need is a 'tree-structure' branch, so I whipped up a quick proposed structure after discussing with Martin this morning. Basically, it is just top-level 'images' and 'qemu.py' folders with the 'distros' at the next sub-level, followed by the 'versions' or 'purposes' on the last sub-level. For example:

wade.lockhart@eriksen~/repos/eid-images$ tree
.
├── images
│   ├── centos
│   │   └── centos8.qcow2
│   ├── debian
│   │   └── debian.qcow2
│   ├── README.md
│   └── ubuntu
│       ├── bionic
│       │   ├── eid-packer-student-machine.qcow2
│       │   └── eid-packer-ubuntu-bionic.qcow2
│       ├── focal
│       │   ├── eid-packer-student-machine.qcow2
│       │   ├── eid-packer-ubuntu-focal.qcow2
│       │   └── eid-packer-ubuntu-server.qcow2
│       └── gcp
├── qemu.py
│   ├── debian-buster-min2.qcow2
│   ├── debian-buster-min.qcow2
│   ├── debian-buster-min.txt
│   ├── eid-packer-ubuntu-focal-base.qcow2
│   ├── eid-packer-ubuntu-focal-integ.qcow2
│   └── README.md
├── README.md
└── scripts
    └── shrink_qcow2.sh

NOTE: This may be easier to follow along in the web interface under the 'tree-structure' branch.

3. I will have a short discussion with Tyler to learn how his mechanisms push to eid-images and what other changes may be required. This information will get added to the generic README.md on how-to add/pull images from the repository.

**Comment by TyKeeling** [comment]
The ansible role is visible in eid-ansible/packer/roles/gen_vm_image/tasks/main.yml. 

<details>
<summary>Here is a snippet</summary>
<br>

```
   - name: Clone repository
      git:
        repo: "{{ git_address }}"
        dest: "{{ tmp_dir.path }}/img"
        depth: 1
        accept_hostkey: yes

    - name: Checkout branch
      command: "git checkout -B {{ output_dir }}"
      args:
        chdir: "{{ tmp_dir.path }}/img"

    - name: Set up git lfs
      shell: "git lfs track \"*.qcow2\"; git add .gitattributes"
      args:
        chdir: "{{ tmp_dir.path }}/img"

    - name: create {{ output_dir }} folder in git repo
      file:
        path: "{{ tmp_dir.path }}/img/{{ output_dir }}"
        state: directory

    - name: Compress qcow image into git repo
      shell: "qemu-img convert -c -O qcow2
{{ playbook_dir }}/{{ output_dir }}/{{ vm_name }}
{{ tmp_dir.path }}/img/{{ output_dir }}/{{ vm_name | regex_replace('\\.qcow2', '-compressed.qcow2') }}"

    - name: Add files to commit (this may take some time)
      command: "git add --all"
      args:
        chdir: "{{ tmp_dir.path }}/img"

    - name: Commit file
      command: "git commit -m '
Automated upload of {{ vm_name }}\n\n
Adds image: {{ playbook_dir }}/{{ vm_name }}\n
Ansible playbook (eid-ansible) version: \"{{ ansible_commit }}\"\n
This is an automated commit. It was generated using the gen_vm_images\n
ansible role.'"
      args:
        chdir: "{{ tmp_dir.path }}/img"

    - name: Push to github
      command: "git push --set-upstream origin {{ output_dir }}"
      args:
        chdir: "{{ tmp_dir.path }}/img"
```

</details>

It can change to match whatever you're up to.
